version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash -c "source /venv/bin/activate && ./manage.py migrate && ./manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - .:/code
    environment:
      REDIS_HOST: redis

  redis:
    image: redis:2.8
